/* Auto-generated by cbindgen. */

#ifndef GRIMLET_H
#define GRIMLET_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Emulator Emulator;

typedef struct Pixel {
  uint8_t r;
  uint8_t g;
  uint8_t b;
  uint8_t a;
} Pixel;

struct Emulator *core_emulator_new(void);

void generate_image(struct Emulator *emulator);

void pixel_func(struct Pixel pixel);

#endif  /* GRIMLET_H */
