/* Auto-generated by cbindgen. */

#ifndef GRIMLET_H
#define GRIMLET_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Emulator Emulator;

typedef struct Pixel {
  uint8_t r;
  uint8_t g;
  uint8_t b;
  uint8_t a;
} Pixel;

struct Emulator *core_init(void);

/**
 * # Safety
 * The `emulator` pointer must be one previously returned by `core_init` and
 * not already freed
 */
void core_drop(struct Emulator *core_ptr);

/**
 * # Safety
 * `emulator` must be a live pointer returned by `core_init`. The returned `*mut Pixel`
 * points into the emulator's internal buffer, must not be freed by the caller, and is
 * invalid after `core_drop`.
 */
struct Pixel *core_get_frame_buffer(struct Emulator *core_ptr);

#endif  /* GRIMLET_H */
